version: '3'
services:
  backend:
    image: thashara/backendv2:5
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb+srv://Thasha:thasha@cluster0.tpcr3a1.mongodb.net/Saloon?retryWrites=true&w=majority

  frontend:
     image: thashara/frontendv2:5
     ports:
      - '3000:3000'